/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/About': RouteRecordInfo<
      '/About',
      '/About',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AddGame': RouteRecordInfo<
      '/AddGame',
      '/AddGame',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Management/[name]': RouteRecordInfo<
      '/Management/[name]',
      '/Management/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/Settings': RouteRecordInfo<
      '/Settings',
      '/Settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SyncSettings': RouteRecordInfo<
      '/SyncSettings',
      '/SyncSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/About.vue': {
      routes:
        | '/About'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AddGame.vue': {
      routes:
        | '/AddGame'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Management/[name].vue': {
      routes:
        | '/Management/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/Settings.vue': {
      routes:
        | '/Settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/SyncSettings.vue': {
      routes:
        | '/SyncSettings'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
