/* tslint:disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBuildInfo() : Promise<BuildInfo> {
    return await TAURI_INVOKE("get_build_info");
},
async openFileOrFolder(path: string) : Promise<Result<OpenPathOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file_or_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppLogDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chooseSaveFile() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_save_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chooseSaveDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_save_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalConfig() : Promise<Result<Config, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addGame(game: GameDraft) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGame(storageKey: string, game: GameDraft) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_game", { storageKey, game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreSnapshot(game: Game, date: string) : Promise<Result<null, RestoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_snapshot", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnapshot(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snapshot", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchDeleteSnapshots(game: Game, dates: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_snapshots", { game, dates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCloudNamespaceGeneration() : Promise<Result<CloudNamespaceGeneration, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cloud_namespace_generation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteGame(game: Game) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameSnapshotsInfo(game: Game) : Promise<Result<GameSnapshots, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_snapshots_info", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify archive integrity by comparing the stored hash against a freshly computed one.
 * Returns `true` if the hash matches (or no stored hash exists), `false` if mismatched.
 */
async verifyArchiveIntegrity(archivePath: string, expectedHash: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_archive_integrity", { archivePath, expectedHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConfig(config: Config) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSnapshot(game: Game, describe: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snapshot", { game, describe }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openBackupFolder(game: Game) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_backup_folder", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameExtraBackups(game: Game) : Promise<Result<ExtraBackupItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_extra_backups", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteExtraBackup(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_extra_backup", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreExtraBackup(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_extra_backup", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExtraBackupFolder(game: Game) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_extra_backup_folder", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkCloudBackend(session: CloudSyncSessionConfig) : Promise<Result<CloudBackendCheckReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_cloud_backend", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectCloudLibrary() : Promise<Result<CloudLibraryStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_cloud_library") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCloudLibrary(confirmed: boolean) : Promise<Result<CloudLibraryStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_cloud_library", { confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reviewCloudLibraryJoin() : Promise<Result<CloudLibraryJoinReview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_cloud_library_join") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinCloudLibrary(decisions: JoinGameDecision[], confirmedReplacements: boolean) : Promise<Result<CloudLibraryJoinOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_cloud_library", { decisions, confirmedReplacements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reviewCloudLibraryCutover() : Promise<Result<CloudLibraryCutoverReview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_cloud_library_cutover") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cutoverCloudLibrary(confirmed: boolean) : Promise<Result<CloudLibraryCutoverOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cutover_cloud_library", { confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCloudArchiveLibrary() : Promise<Result<CloudArchiveLibraryView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cloud_archive_library") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reviewV2GameProgress(gameId: string) : Promise<Result<V2ConflictReview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_v2_game_progress", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async keepV2LocalProgress(gameId: string, manifestRevision: number, localSnapshotId: string) : Promise<Result<KeepLocalProgressOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keep_v2_local_progress", { gameId, manifestRevision, localSnapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async acceptV2RemoteProgress(gameId: string, manifestRevision: number, expectedLocalSnapshotId: string | null, selectedSnapshotId: string) : Promise<Result<AcceptRemoteProgressOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_v2_remote_progress", { gameId, manifestRevision, expectedLocalSnapshotId, selectedSnapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewMaterializeAll() : Promise<Result<MaterializationPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_materialize_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadCloudArchive(gameId: string, snapshotId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_cloud_archive", { gameId, snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadCloudArchive(gameId: string, snapshotId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_cloud_archive", { gameId, snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteV2Snapshot(gameId: string, snapshotId: string, confirmed: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_v2_snapshot", { gameId, snapshotId, confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSharedSnapshotRetention(gameId: string, limit: number | null, confirmed: boolean) : Promise<Result<SnapshotRetentionOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_shared_snapshot_retention", { gameId, limit, confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSnapshotRetentionProtected(gameId: string, snapshotId: string, retentionProtected: boolean, confirmed: boolean) : Promise<Result<SnapshotRetentionOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_retention_protected", { gameId, snapshotId, retentionProtected, confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentDeviceGameStatuses() : Promise<Result<DeviceGameStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_device_game_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeviceGameVisibility(gameId: string, visible: boolean) : Promise<Result<DeviceGameStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_device_game_visibility", { gameId, visible }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeviceGameManaged(gameId: string, managed: boolean, confirmed: boolean) : Promise<Result<DeviceGameStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_device_game_managed", { gameId, managed, confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async evictLocalArchive(gameId: string, snapshotId: string, confirmed: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("evict_local_archive", { gameId, snapshotId, confirmed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async materializeAllCloudArchives() : Promise<Result<MaterializationOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("materialize_all_cloud_archives") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGameSyncMode(gameId: string, mode: SyncMode, initialCatchUp: InitialCatchUpPolicy, liveSave: LiveSaveSyncOptions | null) : Promise<Result<GameSyncModeOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_sync_mode", { gameId, mode, initialCatchUp, liveSave }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudUploadAll(session: CloudSyncSessionConfig) : Promise<Result<BatchSyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloud_upload_all", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudDownloadAll(session: CloudSyncSessionConfig) : Promise<Result<BatchSyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloud_download_all", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelCloudSync() : Promise<Result<CancelCloudSyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_cloud_sync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSnapshotDescription(game: Game, date: string, describe: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_description", { game, date, describe }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setQuickBackupGame(game: Game) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_quick_backup_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGameAutoBackup(gameName: string, autoBackup: AutoBackupConfig | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_auto_backup", { gameName, autoBackup }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGameAutomation(storageKey: string, automation: GameAutomationSettingsDraft | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_automation", { storageKey, automation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGameAutoSaveSettings(storageKey: string, autoBackup: AutoBackupConfig | null, automation: GameAutomationSettingsDraft | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_auto_save_settings", { storageKey, autoBackup, automation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSnapshotCreatedBy(gameName: string, snapshotDate: string, createdBy: CreatedBy) : Promise<Result<GameSnapshots, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_created_by", { gameName, snapshotDate, createdBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutoBackupStatus() : Promise<Result<AutoBackupGameStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_auto_backup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRunningProcesses() : Promise<Result<RunningProcessOption[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_running_processes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolves a path string containing variables to an actual filesystem path
 *
 * This command allows the frontend to resolve paths with variables like <home>, <winAppData>, etc.
 */
async resolvePath(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current device, if not found, returns a default device
 */
async getCurrentDeviceInfo() : Promise<Result<Device, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_device_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleQuickActionSoundPreview(preferences: QuickActionSoundPreferences, effect: QuickActionSoundEffect) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_action_sound_preview", { preferences, effect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSoundPlayback() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_sound_playback") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chooseQuickActionSoundFile() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_quick_action_sound_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the HEAD pointer to a specific snapshot
 * This changes which snapshot new snapshots will branch from
 */
async setSnapshotHead(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_head", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detach a snapshot from its parent, making it a new root node
 */
async detachSnapshot(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detach_snapshot", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new snapshot, optionally branching from a specific parent snapshot
 */
async createSnapshotAt(game: Game, describe: string, parentDate: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snapshot_at", { game, describe, parentDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches the list of importable games from the ludusavi manifest
 */
async fetchLudusaviGames(filterLocalOnly: boolean) : Promise<Result<ImportableGame[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_ludusavi_games", { filterLocalOnly }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets detailed save paths for a specific game from the ludusavi manifest
 */
async getGameSavePaths(gameName: string) : Promise<Result<SavePath[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_save_paths", { gameName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPathPlaceholderCatalog() : Promise<PathPlaceholderDescriptor[]> {
    return await TAURI_INVOKE("get_path_placeholder_catalog");
},
async previewSaveUnitResolution(game: Game, saveUnit: SaveUnit) : Promise<Result<ResolutionReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_save_unit_resolution", { game, saveUnit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGameDeviceBinding(identity: string, binding: GameDeviceBinding) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_device_binding", { identity, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRestoreMapping(identity: string, saveUnitId: number, sourceDimensions: CandidateDimensions, targetCandidateIds: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_restore_mapping", { identity, saveUnitId, sourceDimensions, targetCandidateIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLudusaviManifestStatus() : Promise<Result<LudusaviManifestStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ludusavi_manifest_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLudusaviManifest() : Promise<Result<LudusaviManifestStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ludusavi_manifest") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetLudusaviManifestToBundled() : Promise<Result<LudusaviManifestStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_ludusavi_manifest_to_bundled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkPaths(paths: string[], storeUserId: string | null, installDirs: string[] | null, steamId: number | null) : Promise<Result<PathCheckResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_paths", { paths, storeUserId, installDirs, steamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectGameRoots() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_game_roots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectStoreUserIds() : Promise<Result<StoreUserIdCandidate[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_store_user_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of system font family names
 */
async getSystemFonts() : Promise<string[]> {
    return await TAURI_INVOKE("get_system_fonts");
},
/**
 * Get the local sync state (device-specific, never uploaded).
 */
async getSyncState() : Promise<Result<SyncState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan given directories for visual novels (e.g. Kirikiri2) and return them as GameDrafts.
 */
async scanVns(dirs: string[]) : Promise<Result<GameDraft[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_vns", { dirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available config backup files (newest first).
 */
async listConfigBackups() : Promise<string[]> {
    return await TAURI_INVOKE("list_config_backups");
},
/**
 * Restore config from a backup by index (0 = most recent).
 */
async restoreConfigBackup(index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_config_backup", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync one game by comparing local and remote snapshots.
 */
async syncGame(gameName: string) : Promise<Result<SyncGameOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_game", { gameName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a user-visible cloud sync conflict for one game.
 */
async resolveGameSyncConflict(gameName: string, resolution: ConflictResolution) : Promise<Result<ConflictResolutionOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_game_sync_conflict", { gameName, resolution }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retry syncing the shared configuration to the configured cloud backend.
 */
async syncConfig() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
cloudSyncErrorEvent: CloudSyncErrorEvent,
cloudSyncStatusEvent: CloudSyncStatusEvent,
ipcNotification: IpcNotification,
quickActionCompleted: QuickActionCompleted
}>({
cloudSyncErrorEvent: "cloud-sync-error-event",
cloudSyncStatusEvent: "cloud-sync-status-event",
ipcNotification: "ipc-notification",
quickActionCompleted: "quick-action-completed"
})

/** user-defined constants **/

export const DEFAULT_CONFIG = {"backup_path":"save_data","devices":{},"favorites":[],"games":[],"quick_action":{"enable_notification":true,"enable_sound":true,"game_automations":[],"hotkeys":{"apply":["","",""],"backup":["","",""]},"notify_when_unchanged":true,"quick_action_game_id":null,"sounds":{"failure":{"kind":"default"},"success":{"kind":"default"}}},"settings":{"add_new_to_favorites":false,"appearance":{"custom_font_enabled":false,"ui_font_family":""},"cloud_settings":{"auto_sync_interval":0,"backend":{"type":"Disabled"},"max_concurrency":1,"root_path":"/game-save-manager"},"compression_preset":"Standard","compute_archive_hash":false,"confirm_before_apply_latest":true,"confirm_before_apply_snapshot":true,"default_delete_before_apply":false,"default_expend_favorites_tree":false,"exit_to_tray":true,"extra_backup_when_apply":true,"home_page":"/","locale":"zh_SIMPLIFIED","log_to_file":true,"max_auto_backup_count":0,"max_extra_backup_count":5,"prompt_when_auto_backup":true,"prompt_when_not_described":false,"save_list_expand_behavior":"always_closed","save_list_last_expanded":false,"save_list_sort_direction":"asc","save_list_sort_mode":"saved_order","show_edit_button":false,"verify_archive_before_apply":false,"vn_scan_dirs":[]},"version":"1.9.0"} as const;

/** user-defined types **/

export type AcceptRemoteProgressOutcome = { snapshot_id: string; safety_backup_created: boolean; manifest_revision: number }
export type AppearanceSettings = { custom_font_enabled?: boolean; ui_font_family?: string }
/**
 * Container format used by a Snapshot archive.
 */
export type ArchiveFormat =
/**
 * Historical ZIP Archive Legacy/V1/V2/V3.
 */
"zip" |
/**
 * Metadata-faithful 7z Archive V4.
 */
"seven_z"
/**
 * Per-game auto-backup configuration.
 * Presence (`Some`) enables the timer; absence (`None`) disables it.
 */
export type AutoBackupConfig = {
/**
 * Interval between auto-backups in seconds.
 */
interval_secs: number;
/**
 * Maximum number of auto-backups to keep. `None` = use global setting.
 */
max_backup_count?: number | null }
/**
 * Status of one game's auto-backup timer, returned by `GetStatus`.
 */
export type AutoBackupGameStatus = { game_name: string; interval_secs: number }
export type Backend = { type: "Disabled" } |
/**
 * WebDAV 后端
 * 参考：https://docs.rs/opendal/latest/opendal/services/struct.Webdav.html
 * 不支持 blocking
 */
{ type: "WebDAV"; endpoint: string; username: string; password: string } |
/**
 * Amazon S3 后端
 * 参考：https://docs.rs/opendal/latest/opendal/services/struct.S3.html
 * 不支持 rename 和 blocking
 */
{ type: "S3"; endpoint: string; bucket: string; region: string; access_key_id: string; secret_access_key: string; addressing_style?: S3AddressingStyle }
export type BatchSyncItemReport = { name: string; status: BatchSyncItemStatus }
export type BatchSyncItemStatus = "success" | "cancelled" | { failed: string }
export type BatchSyncReport = { config: BatchSyncItemReport; games: BatchSyncItemReport[] }
export type BuildInfo = { version: string; git_hash: string }
export type CancelCloudSyncResult = "cancelled" | "no_active_operations"
export type CandidateDimensions = { rootId?: string | null; accountId?: string | null; installationId?: string | null; store?: StoreKind | null }
export type CandidateExpression = { id: string; expression: string; logicalAnchor: string; dimensions: CandidateDimensions; caseSensitive: boolean }
export type CloudArchiveDeletionView = { snapshot_id: string; description: string; retryable: boolean }
export type CloudArchiveGameView = { game_id: string; name: string; sync_mode: SyncMode; live_save_process_name: string | null; live_save_snapshot_on_exit: boolean; retention_limit: number | null; managed: boolean; visible: boolean; advertised_head_count: number; snapshots: CloudArchiveSnapshotView[]; pending_deletions: CloudArchiveDeletionView[]; local_count: number; cloud_count: number }
export type CloudArchiveLibraryView = { games: CloudArchiveGameView[]; pending_materialization: boolean }
export type CloudArchiveSnapshotView = { snapshot_id: string; description: string; size: number | null; local_verified: boolean; cloud_verified: boolean; reported_on_devices: string[]; created_by: CreatedBy; retention_protected: boolean }
export type CloudBackendCheckItem = { step: CloudBackendCheckStep; status: CloudBackendCheckItemStatus; critical: boolean; message: string | null }
export type CloudBackendCheckItemStatus = "passed" | "warning" | "failed"
export type CloudBackendCheckOutcome = "available" | "degraded" | "unavailable"
export type CloudBackendCheckReport = { outcome: CloudBackendCheckOutcome; items: CloudBackendCheckItem[] }
export type CloudBackendCheckStep = "prepare_backend" | "list_files" | "write_file" | "read_file" | "verify_content" | "delete_file"
export type CloudLibraryCutoverOutcome = { game_count: number; snapshot_count: number; unavailable_archives: number }
export type CloudLibraryCutoverReview = { game_count: number; snapshot_count: number; declared_bytes: number }
export type CloudLibraryJoinItem = { local_game_id: string; local_name: string; local_fingerprint: string; cloud_names: string[]; cloud_fingerprint: string | null; classification: GameJoinClassification; difference: GameDefinitionDifference }
export type CloudLibraryJoinOutcome = { kind: "active"; game_count: number } | { kind: "review_changed"; game_name: string }
export type CloudLibraryJoinReview = { cloud_game_count: number; items: CloudLibraryJoinItem[] }
export type CloudLibraryStatus = { kind: "empty" } | { kind: "join_required"; game_count: number } | { kind: "cutover_required"; game_count: number } | { kind: "active"; game_count: number }
export type CloudNamespaceGeneration = "legacy_v1" | "v2"
export type CloudSettings = {
/**
 * 同步间隔，单位分钟，为0则不自动同步
 */
auto_sync_interval?: number;
/**
 * 云同步根目录
 */
root_path?: string;
/**
 * 云同步后端设置
 */
backend?: Backend;
/**
 * 最大并发数
 */
max_concurrency?: number }
/**
 * Tauri Event wrapper for CloudSyncError (core type has no Event derive)
 */
export type CloudSyncErrorEvent = { game_name: string | null; error: string }
export type CloudSyncJobInfo = { id: number; description: string; status: CloudSyncJobStatus; error: string | null }
export type CloudSyncJobStatus = "Queued" | "Running" | "Completed" | "Failed" | "Cancelled"
export type CloudSyncSessionConfig = { root_path: string; max_concurrency: number; backend: Backend }
/**
 * Tauri Event wrapper for CloudSyncStatus (core type has no Event derive)
 */
export type CloudSyncStatusEvent = { active_jobs: number; current_description: string | null; jobs: CloudSyncJobInfo[] }
/**
 * User-facing compression presets for backup archives.
 *
 * Each preset maps to a specific `zip::CompressionMethod` and compression level.
 * Old archives using BZip2 remain fully readable regardless of the current preset.
 */
export type CompressionPreset =
/**
 * No compression — fastest backup, largest file size.
 */
"Store" |
/**
 * Deflate level 1 — fast with reasonable compression.
 */
"Fast" |
/**
 * Zstd level 3 — best speed/ratio balance (recommended).
 */
"Standard" |
/**
 * Zstd level 19 — very high compression, slower.
 */
"Best"
/**
 * The software's configuration
 * include the version, backup's location path, games'info,
 * and the settings
 */
export type Config = { version: string; backup_path: string; games: Game[]; settings: Settings; favorites?: FavoriteTreeNode[]; quick_action?: QuickActionsSettings;
/**
 * 设备ID到设备名称的映射
 */
devices?: Partial<{ [key in string]: Device }> }
/**
 * What the user chose to do when a conflict is detected.
 */
export type ConflictResolution = "keep_local" | "accept_remote"
export type ConflictResolutionOutcome = "kept_local" | "accepted_remote"
/**
 * Tracks how a snapshot was created.
 *
 * Forward-compatible: unknown variants from future versions deserialize
 * as `Unknown` — these are never auto-deleted by cleanup logic.
 */
export type CreatedBy =
/**
 * User-created snapshot (manual backup, IPC call, etc.)
 */
"Manual" |
/**
 * Created by the auto-backup timer, subject to retention policy cleanup.
 */
"Timer" |
/**
 * Created via the system tray quick action.
 */
"Tray" |
/**
 * Created via a global hotkey quick action.
 */
"Hotkey" |
/**
 * Created when a monitored game process starts.
 */
"ProcessStart" |
/**
 * Created when a monitored game process exits.
 */
"ProcessExit" |
/**
 * Created by a timer while a monitored game process is running.
 */
"ProcessInterval" |
/**
 * Forward-compat catch-all for variants added in future versions.
 */
"Unknown"
export type Device = { id: string; name: string; resources?: DeviceResource[]; next_resource_id?: number }
export type DeviceGameStatus = { game_id: string; managed: boolean; visible: boolean }
export type DeviceResource = { id: number; source: DeviceResourceSource; kind: DeviceResourceKind }
export type DeviceResourceKind = { type: "gameRoot"; store: StoreKind; path: string } | { type: "storeAccount"; store: StoreKind; user_id: string } | { type: "gameInstallation"; root_id: number; store: StoreKind; install_dir: string; path: string; store_game_id?: string | null }
export type DeviceResourceSource = "manual" | "detected"
export type ExtraBackupItem = {
/**
 * Filename without extension, e.g. `Overwrite_2025-12-22_12-34-56`.
 */
date: string; size: number;
/**
 * File modification time in milliseconds since Unix epoch.
 */
modified_time_ms: number | null }
export type FavoriteTreeNode = { node_id: string; label: string; is_leaf: boolean; children: FavoriteTreeNode[] | null }
/**
 * A game struct contains the save units and the game's launcher
 */
export type Game = { name: string;
/**
 * Filesystem-safe identifier used for local backup directories and remote
 * cloud paths. Derived from `name` via [`super::storage_key::generate_storage_key`]
 * when the game is first created. Once set it never changes, even if the
 * display `name` is later renamed.
 */
storage_key?: string; save_paths: SaveUnit[]; game_paths?: Partial<{ [key in string]: string }>;
/**
 * Monotonically increasing counter for assigning unique save-unit IDs.
 * IDs can be provided by callers (frontend/CLI/FFI), and backend normalization
 * keeps this counter aligned with the highest in-use ID.
 */
next_save_unit_id?: number;
/**
 * Whether this game participates in cloud sync.
 * Defaults to true so existing games are automatically included.
 */
cloud_sync_enabled?: boolean;
/**
 * Per-game auto-backup configuration. `None` = disabled.
 */
auto_backup?: AutoBackupConfig | null;
/**
 * Metadata from Ludusavi manifest import. `None` for manually added games.
 */
ludusavi_meta?: LudusaviMeta | null;
/**
 * Per-Device resource selections for this Game. Missing dimensions remain
 * implicit and become ambiguous if more than one applicable resource exists.
 */
device_bindings: Partial<{ [key in string]: GameDeviceBinding }> }
export type GameAutomationSettings = { storage_key?: string; game_name: string; process_name?: string; on_process_start?: boolean; on_process_exit?: boolean; in_process_interval_secs?: number | null }
export type GameAutomationSettingsDraft = { process_name?: string; on_process_start?: boolean; on_process_exit?: boolean; in_process_interval_secs?: number | null }
export type GameDefinitionDifference = { name_changed: boolean; local_save_unit_count: number; cloud_save_unit_count: number; save_units_changed: boolean; local_recognition: boolean; cloud_recognition: boolean; recognition_changed: boolean }
export type GameDeviceBinding = { rootIds?: number[] | null; accountIds?: number[] | null; installationIds?: number[] | null; restoreMappings: RestoreMappingRule[] }
/**
 * Frontend/IPC input shape for creating/updating a game.
 * Save-unit IDs are assigned and normalized in backend domain logic.
 */
export type GameDraft = { name: string; save_paths: SaveUnitDraft[]; game_paths?: Partial<{ [key in string]: string }>;
/**
 * Metadata from Ludusavi manifest import (optional for manually added games).
 */
ludusavi_meta?: LudusaviMeta | null; device_bindings: Partial<{ [key in string]: GameDeviceBinding }> }
export type GameJoinClassification = "same" | "local_only" | "possible_duplicate" | "game_definition_conflict"
/**
 * A backup list info is a json file in a backup folder for a game.
 * It contains the name of the game,
 * and all backups' path
 */
export type GameSnapshots = { name: string; backups: Snapshot[];
/**
 * Device-specific HEAD pointers. Each device tracks which snapshot new
 * snapshots should branch from locally.
 */
device_heads?: Partial<{ [key in string]: string }>;
/**
 * Monotonically increasing version for sync conflict detection.
 */
sync_version?: number;
/**
 * The device that last modified this metadata.
 */
last_sync_device?: string | null;
/**
 * ISO 8601 timestamp of the last sync operation.
 */
last_sync_timestamp?: string | null }
export type GameSyncModeOutcome = { mode: SyncMode; downloaded: number }
export type GameSyncState = { last_known_local_head?: string | null; last_known_remote_head?: string | null; last_sync_result?: SyncResult | null; last_sync_at?: string | null; pending_action?: PendingAction }
/**
 * Simplified game info for the import dialog
 */
export type ImportableGame = {
/**
 * Game name
 */
name: string;
/**
 * Steam ID if available
 */
steamId: number | null;
/**
 * Install directory names from manifest's `installDir` field
 */
installDirs: string[];
/**
 * Whether this game is already managed
 */
isManaged: boolean;
/**
 * Number of save paths detected
 */
savePathsCount: number }
export type InitialCatchUpPolicy = "keep_remote" | "download_existing"
export type IpcNotification = { level: NotificationLevel; title: string; msg: string }
export type JoinGameAction = "keep_cloud" | "add_local" | "replace_cloud"
export type JoinGameDecision = { local_game_id: string; local_fingerprint: string; cloud_fingerprint: string | null; action: JoinGameAction }
export type KeepLocalProgressOutcome = { snapshot_id: string; prepared_snapshots: number; uploaded_archives: number; manifest_revision: number }
export type LiveSaveSyncOptions = { process_name: string; snapshot_on_exit: boolean }
export type LocalProgressView = { snapshot_id: string; description: string; local_available: boolean; cloud_available: boolean }
export type LudusaviManifestStatus = {
/**
 * Current manifest source: `local`, `bundled`, or `none`.
 */
source: string;
/**
 * Last update time (RFC3339, best-effort).
 */
updatedAt: string | null;
/**
 * A version-like identifier (best-effort, e.g. HTTP ETag).
 */
etag: string | null;
/**
 * Whether a local cached manifest exists.
 */
hasLocal: boolean;
/**
 * Local cache path (if available as a string).
 */
localPath: string | null;
/**
 * Local cache size in bytes (if present).
 */
localBytes: number | null;
/**
 * Bundled manifest size in bytes.
 */
bundledBytes: number }
/**
 * Manifest-derived metadata for games imported from Ludusavi.
 *
 * These fields are **device-independent** (directory names and IDs, not paths)
 * and are safe to persist in config and sync across devices.
 */
export type LudusaviMeta = {
/**
 * Install directory names from the manifest's `installDir` field.
 * e.g. `["100 Orange Juice"]`. Used to resolve `<game>` and `<base>`.
 */
installDirs?: string[];
/**
 * Store-specific game IDs used to resolve `<storeGameId>` in the context
 * of the candidate root or installation.
 */
storeGameIds: StoreGameId[] }
export type ManifestPathCondition = { os?: PlatformKind | null; store?: StoreKind | null }
export type ManifestPathConstraints = { alternatives: ManifestPathCondition[] }
export type ManifestPathPattern = string
export type MaterializationOutcome = { downloaded: number; remaining: number }
export type MaterializationPreview = { snapshot_count: number; total_bytes: number }
export type NotificationLevel = "info" | "warning" | "error"
export type OpenPathOutcome = { status: "opened" } | { status: "warning"; warning: OpenPathWarning }
export type OpenPathWarning = "registryOpenUnsupported"
/**
 * Result of checking a single path
 */
export type PathCheckResult =
/**
 * Path resolved and exists on filesystem
 */
{ status: "ok"; rawPath: string; resolvedPath: string; isFile: boolean } |
/**
 * Path resolved but doesn't exist on filesystem
 */
{ status: "notFound"; rawPath: string; resolvedPath: string } |
/**
 * Registry path
 */
{ status: "registryPath"; rawPath: string; exists: boolean; supported: boolean } |
/**
 * Failed to resolve path variables
 */
{ status: "resolveFailed"; rawPath: string; error: string }
export type PathPlaceholder = "root" | "game" | "base" | "home" | "storeGameId" | "storeUserId" | "osUserName" | "winAppData" | "winLocalAppData" | "winLocalAppDataLow" | "winDocuments" | "winPublic" | "winProgramData" | "winDir" | "xdgData" | "xdgConfig"
export type PathPlaceholderDescriptor = { placeholder: PathPlaceholder; token: string; windowsApplicable: boolean }
export type PendingAction = "none" | "retry_required" | "user_decision_required"
export type PlatformKind = "windows" | "linux" | "macOs"
export type ProgressRelation = "same" | "remote_ahead" | "remote_earlier" | "different_progress" | "no_local_position"
export type QuickActionCompleted = { operation: QuickActionOperation; status: QuickActionStatus; trigger: QuickActionType; game_name: string | null }
export type QuickActionHotkeys = { apply: string[]; backup: string[] }
export type QuickActionOperation = "Backup" | "Apply"
export type QuickActionSoundEffect = "Success" | "Failure"
export type QuickActionSoundPreferences = { enable_sound?: boolean; sounds?: QuickActionSoundSlots }
export type QuickActionSoundSlots = { success?: QuickActionSoundSource; failure?: QuickActionSoundSource }
export type QuickActionSoundSource = { kind: "default" } | { kind: "file"; path: string }
export type QuickActionStatus = "Success" | "Failure" | "SkippedUnchanged"
export type QuickActionType = "Timer" | "Tray" | "Hotkey" | "ProcessStart" | "ProcessExit" | "ProcessInterval"
export type QuickActionsSettings = { quick_action_game_id?: string | null; hotkeys?: QuickActionHotkeys; enable_sound?: boolean; enable_notification?: boolean; notify_when_unchanged?: boolean; sounds?: QuickActionSoundSlots; game_automations?: GameAutomationSettings[] }
export type RemoteProgressCandidate = { snapshot_id: string; description: string; devices: string[]; relation: ProgressRelation; local_unique_snapshots: number; remote_unique_snapshots: number; common_ancestor: string | null; local_available: boolean; cloud_available: boolean }
export type ResolutionDiagnostic = { kind: ResolutionDiagnosticKind; message: string }
export type ResolutionDiagnosticKind = "unknownPlaceholder" | "invalidGlob" | "missingContext" | "unsupportedPlatform" | "noCandidate" | "noMatch" | "multipleCandidates" | "multipleMatches"
export type ResolutionReport = { rawPattern: string; selectionState: ResolutionSelectionState; candidates: CandidateExpression[]; locations: ResolvedSaveLocation[]; diagnostics: ResolutionDiagnostic[] }
export type ResolutionSelectionState = { status: "missing" } | { status: "implicitUnique"; candidate_id: string } | { status: "ambiguous"; candidate_ids: string[] } | { status: "explicit"; candidate_ids: string[] } | { status: "staleSelection"; selected_resource_ids: string[]; candidate_ids: string[] }
export type ResolvedLocationKind = "file" | "directory" | "registry"
export type ResolvedSaveLocation = { path: string; kind: ResolvedLocationKind; candidateId: string; logicalAnchor: string; dimensions: CandidateDimensions }
/**
 * Typed error for restore operations, allowing the frontend to
 * pattern-match on specific failure modes without string parsing.
 */
export type RestoreError = { type: "IntegrityCheckFailed"; expected: string; actual: string } | { type: "BackupNotFound"; date: string } | { type: "DecompressFailed"; message: string } | { type: "Io"; message: string } | { type: "RestoreMappingRequired"; save_unit_id: number; source_dimensions: CandidateDimensions } | { type: "StaleRestoreMapping"; save_unit_id: number; source_dimensions: CandidateDimensions } | { type: "Other"; message: string }
export type RestoreMappingRule = { saveUnitId: number; sourceDimensions: CandidateDimensions; targetCandidateIds: string[] }
export type RunningProcessOption = { name: string; label: string; count: number }
/**
 * How the S3 client addresses buckets.
 *
 * - `PathStyle`: `https://endpoint/bucket/key` (default, works for most generic S3-compatible services)
 * - `VirtualHostedStyle`: `https://bucket.endpoint/key` (required by Tencent COS, Alibaba OSS, etc.)
 * - `Auto`: detect by endpoint host suffix; falls back to virtual-hosted-style for known providers
 */
export type S3AddressingStyle = "PathStyle" | "VirtualHostedStyle" | "Auto"
/**
 * Settings that can be configured by user
 */
export type SaveListExpandBehavior = "always_open" | "always_closed" | "remember_last"
export type SaveListSortMode = "saved_order" | "last_played" | "name"
/**
 * Represents a save file path with its conditions
 */
export type SavePath = {
/**
 * The path pattern
 */
path: string;
/**
 * Tags like "save", "config", etc.
 */
tags: string[]; constraints?: ManifestPathConstraints }
/**
 * A save unit declares one concrete per-Device location or one portable
 * Manifest Path Pattern. Dynamic patterns deliberately do not guess whether
 * their future matches will be files or directories.
 */
export type SaveUnit = { id?: number; source: SaveUnitSource; delete_before_apply?: boolean; enabled?: boolean }
export type SaveUnitDraft = { id?: number | null; source: SaveUnitSource; delete_before_apply?: boolean; enabled?: boolean }
export type SaveUnitSource = { type: "concrete"; unit_type: SaveUnitType; paths?: Partial<{ [key in string]: string }> } | { type: "manifestPattern"; pattern: ManifestPathPattern; constraints?: ManifestPathConstraints }
export type SaveUnitType = "File" | "Folder" |
/**
 * Windows Registry key tree (stored as `registry.reg` inside new archives).
 */
"WinRegistry"
export type Settings = { prompt_when_not_described?: boolean; extra_backup_when_apply?: boolean; confirm_before_apply_latest?: boolean; confirm_before_apply_snapshot?: boolean; show_edit_button?: boolean; prompt_when_auto_backup?: boolean; exit_to_tray?: boolean; cloud_settings?: CloudSettings; locale?: string; default_delete_before_apply?: boolean; default_expend_favorites_tree?: boolean; home_page?: string; log_to_file?: boolean; add_new_to_favorites?: boolean; vn_scan_dirs?: string[]; save_list_expand_behavior?: SaveListExpandBehavior; save_list_last_expanded?: boolean; save_list_sort_mode?: SaveListSortMode; save_list_sort_direction?: SortDirection; max_auto_backup_count?: number;
/**
 * Maximum number of extra overwrite backups to keep per game.
 * Keep the newest N backups; 0 means unlimited.
 */
max_extra_backup_count?: number; appearance?: AppearanceSettings; compression_preset?: CompressionPreset;
/**
 * Compute an XXH3 hash when creating snapshots (for integrity verification).
 */
compute_archive_hash?: boolean;
/**
 * Verify archive hash before applying a snapshot.
 */
verify_archive_before_apply?: boolean }
/**
 * A backup archive containing all data declared by its Save Units.
 * The date is the unique indicator for a backup
 */
export type Snapshot = { date: string; describe: string; path: string;
/**
 * Archive container. Missing values in historical Backups.json default to ZIP.
 */
archive_format?: ArchiveFormat; size?: number;
/**
 * Parent snapshot's date (None means this is a root node)
 */
parent?: string | null;
/**
 * XXH3 hash of the archive file for integrity verification.
 */
archive_hash?: string | null;
/**
 * The device that created this snapshot.
 */
device_id?: string | null;
/**
 * How this snapshot was created.
 */
created_by?: CreatedBy }
export type SnapshotRetentionOutcome = { limit: number | null; deleted: number }
export type SortDirection = "asc" | "desc"
export type StoreGameId = { store: StoreKind; id: string }
export type StoreKind = "steam" | "gog" | "microsoft" | "uplay" | "other"
/**
 * A candidate Steam user ID with metadata for UI display.
 */
export type StoreUserIdCandidate = { userId: string;
/**
 * Stable Steam login name from `config/loginusers.vdf`, when available.
 */
accountName: string | null;
/**
 * Player-facing Steam profile name from `config/loginusers.vdf`, when available.
 */
personaName: string | null;
/**
 * Seconds since UNIX epoch of the `userdata/<id>` directory mtime.
 */
lastModifiedEpochSecs: number | null }
export type SyncGameOutcome = "already_in_sync" | "uploaded" | "downloaded" | "merged" | "conflict"
export type SyncMode = "manual" | "snapshot_sync" | "live_save_sync"
export type SyncResult = "success" | { error: string } | "conflict" | "cancelled"
export type SyncState = { schema_version: number; backend_fingerprint?: string; current_device_id?: string; config_state?: GameSyncState; games?: Partial<{ [key in string]: GameSyncState }> }
export type V2ConflictReview = { game_id: string; manifest_revision: number; local: LocalProgressView | null; candidates: RemoteProgressCandidate[]; requires_choice: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
