[package]
name = "rgsm-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Terminal user interface for Game Save Manager"
license.workspace = true

[[bin]]
name = "rgsm-tui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crossterm = "0.29"
ratatui = "0.30"
rgsm-core.workspace = true
rust-i18n.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
temp-dir.workspace = true
