[package]
name = "rgsm"
version.workspace = true
description = "A user friendly game save manager"
authors = ["Sworld"]
license.workspace = true
repository = ""
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rgsm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = ["bundled-manifest"]
bundled-manifest = ["rgsm-core/bundled-manifest"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
rgsm-core.workspace = true
serde_json.workspace = true
serde.workspace = true
log.workspace = true
tauri = { version = "2.10.3", features = ["tray-icon"] }
tauri-plugin-log = "2.8.0"
rust-i18n.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tauri-plugin-dialog = "2.6.0"
specta.workspace = true
specta-typescript = "0.0.9"
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
rodio = { version = "0.18.1", features = ["flac", "mp3", "vorbis"] }
async-trait.workspace = true
open.workspace = true

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2.3.1"
tauri-plugin-single-instance = "2.4.0"
tauri-plugin-window-state = "2.4.1"

[target.'cfg(windows)'.dependencies]
winreg.workspace = true

[dev-dependencies]
criterion.workspace = true
temp-dir.workspace = true
zip.workspace = true

[[bench]]
name = "compression_algorithms"
harness = false
