/* tslint:disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFileOrFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file_or_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppLogDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chooseSaveFile() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_save_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chooseSaveDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_save_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalConfig() : Promise<Result<Config, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addGame(game: GameDraft) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreSnapshot(game: Game, date: string) : Promise<Result<null, RestoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_snapshot", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnapshot(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snapshot", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchDeleteSnapshots(game: Game, dates: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_snapshots", { game, dates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteGame(game: Game) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameSnapshotsInfo(game: Game) : Promise<Result<GameSnapshots, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_snapshots_info", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify archive integrity by comparing the stored hash against a freshly computed one.
 * Returns `true` if the hash matches (or no stored hash exists), `false` if mismatched.
 */
async verifyArchiveIntegrity(archivePath: string, expectedHash: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_archive_integrity", { archivePath, expectedHash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConfig(config: Config) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSnapshot(game: Game, describe: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snapshot", { game, describe }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openBackupFolder(game: Game) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_backup_folder", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGameExtraBackups(game: Game) : Promise<Result<ExtraBackupItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_extra_backups", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteExtraBackup(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_extra_backup", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreExtraBackup(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_extra_backup", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExtraBackupFolder(game: Game) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_extra_backup_folder", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkCloudBackend(session: CloudSyncSessionConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_cloud_backend", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudUploadAll(session: CloudSyncSessionConfig) : Promise<Result<BatchSyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloud_upload_all", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudDownloadAll(session: CloudSyncSessionConfig) : Promise<Result<BatchSyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloud_download_all", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelCloudSync() : Promise<Result<CancelCloudSyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_cloud_sync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSnapshotDescription(game: Game, date: string, describe: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_description", { game, date, describe }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setQuickBackupGame(game: Game) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_quick_backup_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGameAutoBackup(gameName: string, autoBackup: AutoBackupConfig | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_auto_backup", { gameName, autoBackup }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSnapshotCreatedBy(gameName: string, snapshotDate: string, createdBy: CreatedBy) : Promise<Result<GameSnapshots, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_created_by", { gameName, snapshotDate, createdBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutoBackupStatus() : Promise<Result<AutoBackupGameStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_auto_backup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolves a path string containing variables to an actual filesystem path
 * 
 * This command allows the frontend to resolve paths with variables like <home>, <winAppData>, etc.
 */
async resolvePath(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current device, if not found, returns a default device
 */
async getCurrentDeviceInfo() : Promise<Result<Device, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_device_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleQuickActionSoundPreview(preferences: QuickActionSoundPreferences, effect: QuickActionSoundEffect) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_action_sound_preview", { preferences, effect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSoundPlayback() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_sound_playback") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chooseQuickActionSoundFile() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("choose_quick_action_sound_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the HEAD pointer to a specific snapshot
 * This changes which snapshot new snapshots will branch from
 */
async setSnapshotHead(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_snapshot_head", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detach a snapshot from its parent, making it a new root node
 */
async detachSnapshot(game: Game, date: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detach_snapshot", { game, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new snapshot, optionally branching from a specific parent snapshot
 */
async createSnapshotAt(game: Game, describe: string, parentDate: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snapshot_at", { game, describe, parentDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches the list of importable games from the ludusavi manifest
 */
async fetchLudusaviGames(filterLocalOnly: boolean) : Promise<Result<ImportableGame[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_ludusavi_games", { filterLocalOnly }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets detailed save paths for a specific game from the ludusavi manifest
 */
async getGameSavePaths(gameName: string) : Promise<Result<SavePath[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game_save_paths", { gameName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLudusaviManifestStatus() : Promise<Result<LudusaviManifestStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ludusavi_manifest_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLudusaviManifest() : Promise<Result<LudusaviManifestStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ludusavi_manifest") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetLudusaviManifestToBundled() : Promise<Result<LudusaviManifestStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_ludusavi_manifest_to_bundled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkPaths(paths: string[]) : Promise<Result<PathCheckResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_paths", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets a list of system font family names
 */
async getSystemFonts() : Promise<string[]> {
    return await TAURI_INVOKE("get_system_fonts");
},
/**
 * Get the local sync state (device-specific, never uploaded).
 */
async getSyncState() : Promise<Result<SyncState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available config backup files (newest first).
 */
async listConfigBackups() : Promise<string[]> {
    return await TAURI_INVOKE("list_config_backups");
},
/**
 * Restore config from a backup by index (0 = most recent).
 */
async restoreConfigBackup(index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_config_backup", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync one game by comparing local and remote snapshots.
 */
async syncGame(gameName: string) : Promise<Result<SyncGameOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_game", { gameName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
cloudSyncError: CloudSyncError,
cloudSyncStatus: CloudSyncStatus,
ipcNotification: IpcNotification,
quickActionCompleted: QuickActionCompleted
}>({
cloudSyncError: "cloud-sync-error",
cloudSyncStatus: "cloud-sync-status",
ipcNotification: "ipc-notification",
quickActionCompleted: "quick-action-completed"
})

/** user-defined constants **/

export const DEFAULT_CONFIG = {"backup_path":"save_data","devices":{},"favorites":[],"games":[],"quick_action":{"enable_notification":true,"enable_sound":true,"hotkeys":{"apply":["","",""],"backup":["","",""]},"quick_action_game":null,"sounds":{"failure":{"kind":"default"},"success":{"kind":"default"}}},"settings":{"add_new_to_favorites":false,"appearance":{"custom_font_enabled":false,"ui_font_family":""},"cloud_settings":{"auto_sync_interval":0,"backend":{"type":"Disabled"},"max_concurrency":1,"root_path":"/game-save-manager"},"compression_preset":"Standard","compute_archive_hash":false,"default_delete_before_apply":false,"default_expend_favorites_tree":false,"exit_to_tray":true,"extra_backup_when_apply":true,"home_page":"/","locale":"zh_SIMPLIFIED","log_to_file":true,"max_auto_backup_count":0,"max_extra_backup_count":5,"prompt_when_auto_backup":true,"prompt_when_not_described":false,"save_list_expand_behavior":"always_closed","save_list_last_expanded":false,"show_edit_button":false,"verify_archive_before_apply":false},"version":"1.8.1"} as const;

/** user-defined types **/

export type AppearanceSettings = { custom_font_enabled?: boolean; ui_font_family?: string }
/**
 * Per-game auto-backup configuration.
 * Presence (`Some`) enables the timer; absence (`None`) disables it.
 */
export type AutoBackupConfig = { 
/**
 * Interval between auto-backups in seconds.
 */
interval_secs: number; 
/**
 * Maximum number of auto-backups to keep. `None` = use global setting.
 */
max_backup_count?: number | null }
/**
 * Status of one game's auto-backup timer, returned by `GetStatus`.
 */
export type AutoBackupGameStatus = { game_name: string; interval_secs: number }
export type Backend = { type: "Disabled" } | 
/**
 * WebDAV 后端
 * 参考：https://docs.rs/opendal/latest/opendal/services/struct.Webdav.html
 * 不支持 blocking
 */
{ type: "WebDAV"; endpoint: string; username: string; password: string } | 
/**
 * Amazon S3 后端
 * 参考：https://docs.rs/opendal/latest/opendal/services/struct.S3.html
 * 不支持 rename 和 blocking
 */
{ type: "S3"; endpoint: string; bucket: string; region: string; access_key_id: string; secret_access_key: string }
export type BatchSyncItemReport = { name: string; status: BatchSyncItemStatus }
export type BatchSyncItemStatus = "success" | "cancelled" | { failed: string }
export type BatchSyncReport = { config: BatchSyncItemReport; games: BatchSyncItemReport[] }
export type CancelCloudSyncResult = "cancelled" | "no_active_operations"
export type CloudSettings = { 
/**
 * 同步间隔，单位分钟，为0则不自动同步
 */
auto_sync_interval?: number; 
/**
 * 云同步根目录
 */
root_path?: string; 
/**
 * 云同步后端设置
 */
backend?: Backend; 
/**
 * 最大并发数
 */
max_concurrency?: number }
export type CloudSyncError = { game_name: string | null; error: string }
export type CloudSyncJobInfo = { id: number; description: string; status: CloudSyncJobStatus; error: string | null }
export type CloudSyncJobStatus = "Queued" | "Running" | "Completed" | "Failed" | "Cancelled"
export type CloudSyncSessionConfig = { root_path: string; max_concurrency: number; backend: Backend }
export type CloudSyncStatus = { active_jobs: number; current_description: string | null; jobs: CloudSyncJobInfo[] }
/**
 * User-facing compression presets for backup archives.
 * 
 * Each preset maps to a specific `zip::CompressionMethod` and compression level.
 * Old archives using BZip2 remain fully readable regardless of the current preset.
 */
export type CompressionPreset = 
/**
 * No compression — fastest backup, largest file size.
 */
"Store" | 
/**
 * Deflate level 1 — fast with reasonable compression.
 */
"Fast" | 
/**
 * Zstd level 3 — best speed/ratio balance (recommended).
 */
"Standard" | 
/**
 * Zstd level 19 — very high compression, slower.
 */
"Best"
/**
 * The software's configuration
 * include the version, backup's location path, games'info,
 * and the settings
 */
export type Config = { version: string; backup_path: string; games: Game[]; settings: Settings; favorites?: FavoriteTreeNode[]; quick_action?: QuickActionsSettings; 
/**
 * 设备ID到设备名称的映射
 */
devices?: Partial<{ [key in string]: Device }> }
/**
 * Tracks how a snapshot was created.
 * 
 * Forward-compatible: unknown variants from future versions deserialize
 * as `Unknown` — these are never auto-deleted by cleanup logic.
 */
export type CreatedBy = 
/**
 * User-created snapshot (manual backup, IPC call, etc.)
 */
"Manual" | 
/**
 * Created by the auto-backup timer, subject to retention policy cleanup.
 */
"Timer" | 
/**
 * Forward-compat catch-all for variants added in future versions.
 */
"Unknown"
export type Device = { id: string; name: string }
export type ExtraBackupItem = { 
/**
 * Filename without extension, e.g. `Overwrite_2025-12-22_12-34-56`.
 */
date: string; size: number; 
/**
 * File modification time in milliseconds since Unix epoch.
 */
modified_time_ms: number | null }
export type FavoriteTreeNode = { node_id: string; label: string; is_leaf: boolean; children: FavoriteTreeNode[] | null }
/**
 * A game struct contains the save units and the game's launcher
 */
export type Game = { name: string; save_paths: SaveUnit[]; game_paths?: Partial<{ [key in string]: string }>; 
/**
 * Monotonically increasing counter for assigning unique save-unit IDs.
 * IDs can be provided by callers (frontend/CLI/FFI), and backend normalization
 * keeps this counter aligned with the highest in-use ID.
 */
next_save_unit_id?: number; 
/**
 * Whether this game participates in cloud sync.
 * Defaults to true so existing games are automatically included.
 */
cloud_sync_enabled?: boolean; 
/**
 * Per-game auto-backup configuration. `None` = disabled.
 */
auto_backup?: AutoBackupConfig | null }
/**
 * Frontend/IPC input shape for creating/updating a game.
 * Save-unit IDs are assigned and normalized in backend domain logic.
 */
export type GameDraft = { name: string; save_paths: SaveUnitDraft[]; game_paths?: Partial<{ [key in string]: string }> }
/**
 * A backup list info is a json file in a backup folder for a game.
 * It contains the name of the game,
 * and all backups' path
 */
export type GameSnapshots = { name: string; backups: Snapshot[]; 
/**
 * Device-specific HEAD pointers. Each device tracks which snapshot new
 * snapshots should branch from locally.
 */
device_heads?: Partial<{ [key in string]: string }>; 
/**
 * Monotonically increasing version for sync conflict detection.
 */
sync_version?: number; 
/**
 * The device that last modified this metadata.
 */
last_sync_device?: string | null; 
/**
 * ISO 8601 timestamp of the last sync operation.
 */
last_sync_timestamp?: string | null }
export type GameSyncState = { last_known_local_head?: string | null; last_known_remote_head?: string | null; last_sync_result?: SyncResult | null; last_sync_at?: string | null; pending_action?: PendingAction }
/**
 * Simplified game info for the import dialog
 */
export type ImportableGame = { 
/**
 * Game name
 */
name: string; 
/**
 * Steam ID if available
 */
steamId: number | null; 
/**
 * Whether this game is already managed
 */
isManaged: boolean; 
/**
 * Number of save paths detected
 */
savePathsCount: number }
export type IpcNotification = { level: NotificationLevel; title: string; msg: string }
export type LudusaviManifestStatus = { 
/**
 * Current manifest source: `local` or `bundled`.
 */
source: string; 
/**
 * Last update time (RFC3339, best-effort).
 */
updatedAt: string | null; 
/**
 * A version-like identifier (best-effort, e.g. HTTP ETag).
 */
etag: string | null; 
/**
 * Whether a local cached manifest exists.
 */
hasLocal: boolean; 
/**
 * Local cache path (if available as a string).
 */
localPath: string | null; 
/**
 * Local cache size in bytes (if present).
 */
localBytes: number | null; 
/**
 * Bundled manifest size in bytes.
 */
bundledBytes: number }
export type NotificationLevel = "info" | "warning" | "error"
/**
 * Result of checking a single path
 */
export type PathCheckResult = 
/**
 * Path resolved and exists on filesystem
 */
{ status: "ok"; rawPath: string; resolvedPath: string; isFile: boolean } | 
/**
 * Path resolved but doesn't exist on filesystem
 */
{ status: "notFound"; rawPath: string; resolvedPath: string } | 
/**
 * Registry path
 */
{ status: "registryPath"; rawPath: string; exists: boolean; supported: boolean } | 
/**
 * Failed to resolve path variables
 */
{ status: "resolveFailed"; rawPath: string; error: string }
export type PendingAction = "none" | "retry_required" | "user_decision_required"
export type QuickActionCompleted = { operation: QuickActionOperation; status: QuickActionStatus; trigger: QuickActionType; game_name: string | null }
export type QuickActionHotkeys = { apply: string[]; backup: string[] }
export type QuickActionOperation = "Backup" | "Apply"
export type QuickActionSoundEffect = "Success" | "Failure"
export type QuickActionSoundPreferences = { enable_sound?: boolean; sounds?: QuickActionSoundSlots }
export type QuickActionSoundSlots = { success?: QuickActionSoundSource; failure?: QuickActionSoundSource }
export type QuickActionSoundSource = { kind: "default" } | { kind: "file"; path: string }
export type QuickActionStatus = "Success" | "Failure"
export type QuickActionType = "Timer" | "Tray" | "Hotkey"
export type QuickActionsSettings = { quick_action_game?: Game | null; hotkeys?: QuickActionHotkeys; enable_sound?: boolean; enable_notification?: boolean; sounds?: QuickActionSoundSlots }
/**
 * Typed error for restore operations, allowing the frontend to
 * pattern-match on specific failure modes without string parsing.
 */
export type RestoreError = { type: "IntegrityCheckFailed"; expected: string; actual: string } | { type: "BackupNotFound"; date: string } | { type: "DecompressFailed"; message: string } | { type: "Io"; message: string } | { type: "Other"; message: string }
/**
 * Settings that can be configured by user
 */
export type SaveListExpandBehavior = "always_open" | "always_closed" | "remember_last"
/**
 * Represents a save file path with its conditions
 */
export type SavePath = { 
/**
 * The path pattern
 */
path: string; 
/**
 * Tags like "save", "config", etc.
 */
tags: string[] }
/**
 * A save unit declares one of the files/folders
 * that should be backup for a game.
 * 
 * The `id` field is a stable identifier used as the index prefix in V2 archives.
 * Unlike positional indices, it does not change when save units are added or removed,
 * ensuring old archives can always be restored correctly. The backend will
 * normalize duplicated IDs when persisting config.
 */
export type SaveUnit = { 
/**
 * Stable identifier for this save unit, used as archive entry prefix in V2 format.
 * Provided by the caller (frontend/CLI/FFI) and kept unique by backend normalization.
 */
id?: number; unit_type: SaveUnitType; paths?: Partial<{ [key in string]: string }>; delete_before_apply?: boolean; enabled?: boolean }
/**
 * Frontend/IPC input shape for save-unit editing.
 * Existing rows may provide `id` to preserve archive compatibility during edits;
 * backend logic allocates IDs for new rows and normalizes duplicates.
 */
export type SaveUnitDraft = { id?: number | null; unit_type: SaveUnitType; paths?: Partial<{ [key in string]: string }>; delete_before_apply?: boolean; enabled?: boolean }
/**
 * The kind of data a save unit backs up.
 */
export type SaveUnitType = "File" | "Folder" | 
/**
 * Windows Registry key tree (stored as `registry.json` inside the archive).
 */
"WinRegistry"
export type Settings = { prompt_when_not_described?: boolean; extra_backup_when_apply?: boolean; show_edit_button?: boolean; prompt_when_auto_backup?: boolean; exit_to_tray?: boolean; cloud_settings?: CloudSettings; locale?: string; default_delete_before_apply?: boolean; default_expend_favorites_tree?: boolean; home_page?: string; log_to_file?: boolean; add_new_to_favorites?: boolean; save_list_expand_behavior?: SaveListExpandBehavior; save_list_last_expanded?: boolean; max_auto_backup_count?: number; 
/**
 * Maximum number of extra overwrite backups to keep per game.
 * Keep the newest N backups; 0 means unlimited.
 */
max_extra_backup_count?: number; appearance?: AppearanceSettings; compression_preset?: CompressionPreset; 
/**
 * Compute an XXH3 hash when creating snapshots (for integrity verification).
 */
compute_archive_hash?: boolean; 
/**
 * Verify archive hash before applying a snapshot.
 */
verify_archive_before_apply?: boolean }
/**
 * A backup is a zip file that contains
 * all the file that the save unit has declared.
 * The date is the unique indicator for a backup
 */
export type Snapshot = { date: string; describe: string; path: string; size?: number; 
/**
 * Parent snapshot's date (None means this is a root node)
 */
parent?: string | null; 
/**
 * XXH3 hash of the archive file for integrity verification.
 */
archive_hash?: string | null; 
/**
 * The device that created this snapshot.
 */
device_id?: string | null; 
/**
 * How this snapshot was created.
 */
created_by?: CreatedBy }
export type SyncGameOutcome = "already_in_sync" | "uploaded" | "downloaded" | "merged" | "conflict"
export type SyncResult = "success" | { error: string } | "conflict" | "cancelled"
export type SyncState = { schema_version: number; backend_fingerprint?: string; current_device_id?: string; config_state?: GameSyncState; games?: Partial<{ [key in string]: GameSyncState }> }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
